### ISSUE TITLE
Should it be allowed to systematically target questions that are answered by a specific OP

### ISSUE THREAD

**Issue by rschrieken** [SO-Close-Vote-Reviewers/room-meeting-topics#20] opened 2018-08-14 16:04 UTC
In SOCVR we allow cv-pls and delv-pls to close and remove questions. 

While we all agree we moderate content of a post it is possible by  posting cv-pls and subsequent delv-pls to remove the answers as well that were posted on these questions. 

What if those cv-pls and delv-pls are  strategically posted to target certain OP's that posts answers to duplicate and/or low quality questions. Is that something we want to detect, warn and/or forbid.?

If so, how? if not, why is this okay and defend-able on meta when oposition is raised?

a bit of context [here](https://meta.stackoverflow.com/questions/370539/repeated-behavior-of-user-harvesting-reputation-from-known-duplicates-next-step)

**Comment by NathanOliver1** [comment] 2018-08-14 16:17
I'm not really seeing too much of an issue with this for closing / deleting questions.  Yes, the person making the request might have lost objectivity but those of us in the room are looking at the request in isolation.  We most likely won't know about this users history and will be judging if the Q is worthy of being open/not deleted by it's own merits.  I also don't have a problem deleting nth dupe questions as they aren't adding anything to the system.  Yes, sign posts are good, but we don't need 1000 of them, especially when they add no new search terms.

**Comment by makyen** [comment] 2018-08-24 06:47
My problem with this is that it is user targeting, just not of the question OP. User targeting is something we really should not permit. 

I don't have a problem with deleting duplicates that are not good signposts, but that is not the issue here. The issue is user targeting.

The solution that's advocated in [the answer by Jean-François Fabre](https://meta.stackoverflow.com/a/370567) to [Repeated behavior of user harvesting reputation from known duplicates, next steps to do?](https://meta.stackoverflow.com/q/370539) is that the user who desires to do such targeting select a larger class of (duplicate) questions, which happens to include those questions which are commonly answered by the user who it's desired to target. While it is an improvement to make a point of targeting a class of questions, rather than just targeting a particular answerer, the motivation bothers me (i.e. that it's motivated by user targeting, but tries to hide it in a larger quantity of requests).

Our current tooling neither highlights the answer authors (i.e. unlike the question OP, they are not stated in the request, so harder to notice), nor do our automatic checks currently check for multiple requests containing the same answerer. I don't know about anyone else, but, personally, when evaluating questions for CV/DelV action I don't pay attention to the answers' authors. I rarely notice who the question author is. Thus, at least for me, noticing that someone is targeting a specific answerer would be possible, but something would likely need to draw my attention to the fact that more than one answer by that user was on questions.

My opinion is that it's not acceptable for us to permit targeting users. Our moderation efforts should be about *content*, not about selecting to moderate questions and/or answers based on who wrote them.

**Closed as completed** 2018-09-08 16:06 UTC
Labels: suggested-topic
